module.exports = {
  shoes: [
    {
      id: 1,
      title: 'Black Snickers',
      brand: 'Others',
      image: 'http://localhost:3001/assets/images/others-black-1-600x600.jpg',
      color: 'Black',
      price: 1295,
      discount: 35,
      rating: 4.3,
    },
    {
      id: 2,
      title: 'Black Snickers',
      brand: 'Others',
      image: 'http://localhost:3001/assets/images/others-black-2-600x600.jpg',
      color: 'Black',
      price: 1325,
      discount: 35,
      rating: 4.3,
    },
    {
      id: 3,
      title: 'White Snickers',
      brand: 'Nike',
      image: 'http://localhost:3001/assets/images/nike-white-1-600x600.jpg',
      color: 'White',
      price: 1450,
      discount: 40,
      rating: 4.6,
    },
    {
      id: 4,
      title: 'High Hills',
      brand: 'Others',
      image: 'http://localhost:3001/assets/images/others-black-hills-1-600x600.jpg',
      color: 'Black',
      price: 1375,
      discount: 40,
      rating: 4.3,
    },
    {
      id: 5,
      title: 'Black Leather Shoes',
      brand: 'Others',
      image: 'http://localhost:3001/assets/images/others-black-leather-1-600x600.jpg',
      color: 'Black',
      price: 2425,
      discount: 30,
      rating: 4.3,
    },
    {
      id: 6,
      title: 'Blue Snickers',
      brand: 'Others',
      image: 'http://localhost:3001/assets/images/others-blue-1-600x600.jpeg',
      color: 'Blue',
      price: 3420,
      discount: 35,
      rating: 4.3,
    },
  ]
};
