module.exports = {
  shoes: [
    {
      id: 1,
      title: 'Blue Snickers',
      brand: 'Addidas',
      image: './photos/addidas-blue-1-600x600.jpg',
      color: 'Blue',
      price: 325,
      discount: 20,
      rating: 4.4,
    },
    {
      id: 2,
      title: 'Black Snickers',
      brand: 'Others',
      image: './photos/others-black-1-600x600.jpg',
      color: 'Black',
      price: 295,
      discount: 25,
      rating: 4.3,
    },
    {
      id: 3,
      title: 'Black Snickers',
      brand: 'Others',
      image: './photos/others-black-2-600x600.jpg',
      color: 'Black',
      price: 325,
      discount: 25,
      rating: 4.3,
    },
    {
      id: 4,
      title: 'White Snickers',
      brand: 'Nike',
      image: './photos/nike-white-1-600x600.jpg',
      color: 'White',
      price: 450,
      discount: 20,
      rating: 4.6,
    },
    {
      id: 5,
      title: 'Snickers',
      brand: 'Addidas',
      image: './photos/addidas-green-1-600x600.jpg',
      color: 'Green',
      price: 400,
      discount: 25,
      rating: 4.5,
    },
    {
      id: 6,
      title: 'High Hills',
      brand: 'Others',
      image: './photos/others-black-hills-1-600x600.jpg',
      color: 'Black',
      price: 375,
      discount: 25,
      rating: 4.3,
    },
    {
      id: 7,
      title: 'White Snickers',
      brand: 'Nike',
      image: './photos/nike-white-2-600x600.jpg',
      color: 'White',
      price: 450,
      discount: 20,
      rating: 4.6,
    },
    {
      id: 8,
      title: 'Blue Snickers',
      brand: 'Addidas',
      image: './photos/addidas-blue-2-600x600.jpg',
      color: 'Blue',
      price: 400,
      discount: 25,
      rating: 4.5,
    },
    {
      id: 9,
      title: 'Black Leather Shoes',
      brand: 'Others',
      image: './photos/others-black-leather-1-600x600.jpg',
      color: 'Black',
      price: 425,
      discount: 25,
      rating: 4.3,
    },
    {
      id: 10,
      title: 'White Snickers',
      brand: 'Addidas',
      image: './photos/addidas-white-1-600x600.jpeg',
      color: 'White',
      price: 400,
      discount: 25,
      rating: 4.5,
    },
    {
      id: 11,
      title: 'Blue Snickers',
      brand: 'Others',
      image: './photos/others-blue-1-600x600.jpeg',
      color: 'Blue',
      price: 420,
      discount: 25,
      rating: 4.3,
    },
  ]
};
